name: docker build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      -
        uses: actions/checkout@v1
      -
        name: "Set up Python"
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      -
        env:
          OSG_ACCESS: "${{secrets.OSG_ACCESS}}"
        name: "Preparing ssh stuff"
        run: "bash -e tools/docker_build_prepssh.sh"
      -
        env:
          DOCKER_IMG: igwn/base:el8
          PYCBC_CONTAINER: pycbc_rhel_virtualenv
          DOCKER_SECURE_ENV_VARS: true
        name: "Creating the virtual environment"
        run: "bash -e tools/docker_build_and_test.sh"

