name: Build Wheels

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  workflow_defaults:
    uses: ./.github/workflows/workflow-defaults.yml
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: workflow_defaults
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-14]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ needs.workflow_defaults.outputs.python-version }}
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: cp311-* cp312-* cp313-*
          CIBW_SKIP: "*musllinux*"
          CIBW_ARCHS_MACOS: x86_64 arm64
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.os }}
          path: ./wheelhouse/*.whl
  deploy_pypi:
    name: Package and publish to PyPI
    runs-on: ubuntu-24.04
    needs: [build_wheels, workflow_defaults]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ needs.workflow_defaults.outputs.python-version }}
      - uses: actions/download-artifact@v4.1.7
        with:
          pattern: wheel-*
          merge-multiple: true
          path: dist/
      - name: Build source distribution
        run: |
          python -c 'import setuptools ; print("setuptools version", setuptools.__version__)'
          pip install pip setuptools --upgrade
          python setup.py sdist
          ls -lh dist
      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
        with:
          password: ${{ secrets.pypi_password }}
