name: run small inference workflow using pegasus + condor

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v1
    - name: Load defaults
      id: defaults
      uses: ./.github/actions/defaults
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ steps.defaults.outputs.python_version }}
    - name: install condor and pegasus
      uses: ./.github/actions/install-htcondor-pegasus
    - name: install system dependecies
      uses: ./.github/actions/install-system-deps
    - name: Install pycbc
      run: |
        python -m pip install --upgrade pip setuptools
        pip install GitPython # This shouldn't really be needed!
        pip install -r requirements.txt
        pip install .
    - name: retrieving data
      run: bash -e examples/inference/single/get.sh
    - name: generating, submitting and running workflow
      run: |
        cp examples/inference/single/single.ini ./
        cp examples/workflow/inference/small_test/*.ini ./
        bash -e examples/workflow/inference/small_test/gen.sh
        condor_status
        cd gw_output
        ./status
        python ../examples/search/check_job.py
        find submitdir/work/ -type f -name '*.tar.gz' -delete
    - name: store log files
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: gw_output/submitdir/work
    - name: store result page
      uses: actions/upload-artifact@v4
      with:
        name: results
        path: html
