name: tutorial tests

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 60
      matrix:
        os: [ubuntu-24.04]
        python-version: ['3.10', '3.11', '3.12']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: installing packages
      run: |
        sudo apt-get -o Acquire::Retries=3 update
        sudo apt-get -o Acquire::Retries=3 install *fftw3* mpi intel-mkl*
        pip install tox pip "setuptools<82.0.0" notebook --upgrade
        pip install .
    - name: retrieving pycbc tutorials
      run: |
        git clone https://github.com/gwastro/PyCBC-Tutorials
    - name: running pycbc tutorials
      run: |
        cd PyCBC-Tutorials
        ./test_notebooks
